
workspace 'FillrPods.xcworkspace'
use_frameworks!

plugin 'cocoapods-art', :sources => [
  'fillr-ios-core-sdk', # core sdk is required by all products
  'fillr-ios-autofill-sdk',
  'fillr-ios-cartscraper-sdk',
]

# Integrating static library
target "Autofill" do
    pod 'fillr-autofill-static-xcframeworks', '3.0.0'
end

target "CartScraper" do
    pod 'fillr-cartscraper-static-xcframeworks', '3.0.0'
end


## Integrating dynamic framework
#target "Autofill" do
#    pod 'fillr-autofill-dynamic-xcframeworks', '3.0.0'
#end
#
#target "CartScraper" do
#    pod 'fillr-cartscraper-dynamic-xcframeworks', '3.0.0'
#end


# 1. Add the repository
# pod repo-art add fillr-ios-core-sdk https://fillr.jfrog.io/fillr/api/pods/fillr-ios-core-sdk
# pod repo-art add fillr-ios-autofill-sdk https://fillr.jfrog.io/fillr/api/pods/fillr-ios-autofill-sdk
# pod repo-art add fillr-ios-cartscraper-sdk https://fillr.jfrog.io/fillr/api/pods/fillr-ios-cartscraper-sdk

# 2. Update the repository
#pod repo-art update fillr-ios-core-sdk
#pod repo-art update fillr-ios-autofill-sdk
#pod repo-art update fillr-ios-cartscraper-sdk

# 3. Install pods
#pod install

