
workspace 'FillrPods.xcworkspace'
use_frameworks!

plugin 'cocoapods-art', :sources => [
  'fillr-ios-core-sdk', # core sdk is required by all products
  'fillr-ios-autofill-sdk',
  'fillr-ios-cartscraper-sdk',
  'fillr-ios-product-page-scraper-sdk',
  'fillr-ios-page-classifier-sdk',
  'fillr-ios-order-scraper-sdk',
]

# Integrating static library
target "Autofill" do
    pod 'fillr-autofill-static-xcframeworks', '1.0.0'
end

target "CartScraper" do
    pod 'fillr-cartscraper-static-xcframeworks', '1.0.0'
end

target "ProductScraper" do
    pod 'fillr-product-page-scraper-static-xcframeworks', '1.0.0'
end

target "OrderScraper" do
    pod 'fillr-order-scraper-static-xcframeworks', '1.0.0'
end

target "PageClassifier" do
    pod 'fillr-page-classifier-static-xcframeworks', '1.0.0'
end

# Integrating dynamic framework
#target "Autofill" do
#    pod 'fillr-autofill-dynamic-xcframeworks', '1.0.0'
#end
#
#target "CartScraper" do
#    pod 'fillr-cartscraper-dynamic-xcframeworks', '1.0.0'
#end
#
#target "ProductScraper" do
#    pod 'fillr-product-page-scraper-dynamic-xcframeworks', '1.0.0'
#end
#
#target "OrderScraper" do
#    pod 'fillr-order-scraper-dynamic-xcframeworks', '1.0.0'
#end
#
#target "PageClassifier" do
#    pod 'fillr-page-classifier-dynamic-xcframeworks', '1.0.0'
#end



# 1. Add the repository
#pod repo-art add fillr-ios-core-sdk https://fillr.jfrog.io/fillr/api/pods/fillr-ios-core-sdk
#pod repo-art add fillr-ios-autofill-sdk https://fillr.jfrog.io/fillr/api/pods/fillr-ios-autofill-sdk
#pod repo-art add fillr-ios-cartscraper-sdk https://fillr.jfrog.io/fillr/api/pods/fillr-ios-cartscraper-sdk
#pod repo-art add fillr-ios-product-page-scraper-sdk https://fillr.jfrog.io/fillr/api/pods/fillr-ios-product-page-scraper-sdk
#pod repo-art add fillr-ios-page-classifier-sdk https://fillr.jfrog.io/fillr/api/pods/fillr-ios-page-classifier-sdk
#pod repo-art add fillr-ios-order-scraper-sdk https://fillr.jfrog.io/fillr/api/pods/fillr-ios-order-scraper-sdk

# 2. Update the repository
#pod repo-art update fillr-ios-core-sdk
#pod repo-art update fillr-ios-autofill-sdk
#pod repo-art update fillr-ios-cartscraper-sdk
#pod repo-art update fillr-ios-product-page-scraper-sdk
#pod repo-art update fillr-ios-page-classifier-sdk
#pod repo-art update fillr-ios-order-scraper-sdk

# 3. Install pods
#pod install

