
workspace 'FillrPods.xcworkspace'

plugin 'cocoapods-art', :sources => [
  'fillr-ios-core-sdk',
  'fillr-ios-autofill-sdk',
]

use_frameworks!
target "FillrPods" do
    pod 'fillr-autofill-static-xcframeworks', '1.2.0'
    project "FillrPods.xcodeproj"
end

#pod repo-art add fillr-ios-core-sdk https://fillr.jfrog.io/fillr/api/pods/fillr-ios-core-sdk
#pod repo-art add fillr-ios-autofill-sdk https://fillr.jfrog.io/fillr/api/pods/fillr-ios-autofill-sdk

#pod repo-art update fillr-ios-sdk
#pod install
#pod cache clean fillr-autofill-static-xcframeworks
